linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: error-return
        severity: error
      - name: error-naming
        severity: error
      - name: errorf
        severity: error
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-naming
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range
        severity: warning
      - name: range-val-in-closure
        severity: error
      - name: range-val-address
        severity: error
      - name: waitgroup-by-value
        severity: error
      - name: atomic
        severity: error
      - name: empty-lines
        severity: warning
      - name: line-length-limit
        severity: warning
        arguments:
          - 120

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

